"""Add LearningInsight model

Revision ID: 84d03a5d2445
Revises: 2d3793ae3a88
Create Date: 2026-07-07 14:08:25.755188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d03a5d2445'
down_revision: Union[str, None] = '2d3793ae3a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('strong_concepts', sa.Text(), nullable=True),
    sa.Column('weak_concepts', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_insights_id'), 'learning_insights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_insights_id'), table_name='learning_insights')
    op.drop_table('learning_insights')
    # ### end Alembic commands ###
